config/routes.rb
Rails.application.routes.draw do
  resources :products

  devise_for :users
  get 'home/index'

  resources :orders

  root 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @orders = Order.all
    @order = Order.new
    @product_first = Product.first
    @product_last = Product.last

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :count, :adress, :user_name, :telephone)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @orders = Order.all
    
    respond_to do |format|
      if @order.save
        format.html { render :index }
        # format.html { redirect_to @order, notice: 'Order was successfully created.' }
        # format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :count, :adress, :user_name, :telephone)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :currency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<html>

<head>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <title>Продажа автоклавов в Минске и по территории Беларуси</title>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width">
  <meta name="google-site-verification" content="9SoZ4UGqHpVGsJ86WunwkBfhtKVm02WyWc0gCrskRzs" />
  <meta name='yandex-verification' content='456c51f172eff36c' />
  <meta name="description" content= "Купить автоклав в Минске не дорого" />
  <meta name="keywords" content= "Купить автоклав в Минске, Автоклав, тушенка, автоклав в Минске, автоклав стерилизатор, стерилизация консервов, скороварка автоклав, Купить автоклав в Минске, автоклав в Беларуси, купить автоклав новый, тушенка, консерва, мясо, овощи в автоклаве, надувные лодки, купить надувные лодки, лодки под мотор, рыболовные плавсредства" />
  <!--[if lt IE 9]><script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <link rel="stylesheet" href="/assets/style.css" media="screen">
  <!--[if lte IE 7]><link rel="stylesheet" href="style.ie7.css" media="screen" /><![endif]-->
  <link rel="stylesheet" href="/assets/style.responsive.css" media="all">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Noto+Sans&amp;subset=latin">
  <script src="/assets/jquery.js"></script>
  <script src="/assets/script.js"></script>
  <script src="/assets/script.responsive.js"></script>
  <style>.art-content .art-postcontent-0 .layout-item-0 { margin-bottom: 10px;  }
    .art-content .art-postcontent-0 .layout-item-1 { border-top-style:solid;border-right-style:solid;border-bottom-style:solid;border-left-style:solid;border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-top-color:#D9D9D9;border-right-color:#D9D9D9;border-bottom-color:#D9D9D9;border-left-color:#D9D9D9;  }
    .art-content .art-postcontent-0 .layout-item-2 { color: #2B2B2B; padding-right: 10px;padding-left: 10px;  }
    .ie7 .art-post .art-layout-cell {border:none !important; padding:0 !important; }
    .ie6 .art-post .art-layout-cell {border:none !important; padding:0 !important; }
  </style>
</head>
<body>




  <div id="art-main">
    <div class="art-sheet clearfix">
      <nav class="art-nav">
        <ul class="art-hmenu">
          <li><a href="/">Главная</a></li>
          <li><a href="/orders">Заказы</a></li>
        </ul>
        <div class="right">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Регистрация", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Вход в личный кабинет", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </nav>
      <header class="art-header">
        <div class="art-shapes">
          <div class="art-object260529295" data-left="0.09%"></div>
          <div class="art-object157058295" data-left="99.91%"></div>
          <div class="art-object1865807942" data-left="48.94%"></div>
          <div class="art-object1302216706" data-left="51.91%"></div>
        </div>
        <h1 class="art-headline" data-left="47.64%">
          <a href="#">Автоклавы для стерилизации консервов</a>
        </h1>
        <h2 class="art-slogan" data-left="49.57%">Телефоны: +37529 7379222 (МТС) или +37529 3319156 (Velcom)</h2>
      </header>
      <div class="art-layout-wrapper">
        <div class="art-content-layout">
          <div class="art-content-layout-row">
            <div class="art-layout-cell art-sidebar1"><div class="art-block clearfix">
              <div class="art-blockheader">
                <h3 class="t">Советы покупателю:</h3>
              </div>
              <div class="art-blockcontent">
                <ul>
                  <li style="text-align: left;">
                    <span style="font-size: 14px;">Если вы ведете не маленькое домашнее хозяйство, занимаетесь охотой или рыбалкой и собираетесь часто готовить закатки, тогда Вам следует приобрести автоклав <span style="font-weight: bold;">на 30 литров</span>.&nbsp;<br></span>
                  </li>
                  <li style="text-align: left;">
                    <span style="font-size: 14px;">Если вы проживаете в городе и в течении года всего лишь &nbsp;пару раз ездите на дачу, тогда Вам вполне будет достаточно автоклава <span style="font-weight: bold;">на 24 литра</span>.</span>
                  </li><li style="text-align: left;">
                  <span style="font-size: 14px;">Не рекомендуем покупать автоклав <span style="font-weight: bold;">на 20 литров</span>,&nbsp;<span style="color: rgb(64, 64, 64); text-align: justify;">так как размеры практически такие же как и у 24-х литрового, а вместительность пол-литровых банок в два раза меньше.&nbsp;</span></span>
                </li>
                <li style="text-align: left;">
                  <span style="font-size: 14px;"><span style="text-align: justify;">Отличным решение будет <span style="font-weight: bold;">подарить автоклав</span> кому-нибудь из близких или родных на любые праздники.</span><br></span>
                </li>
                <li style="text-align: left;">
                  <span style="font-size: 14px;">Рекомендуем после пользования автоклавом <span style="font-weight: bold;">просушить</span> его и хранить в сухом месте.</span>
                </li>
                <li style="text-align: left;">
                  <span style="font-size: 14px;">На белорусском рынке имеются в наличии и <span style="font-weight: bold;">российские автоклавы</span>, стоимостью от 5 млн. рублей и из нержавейки. Процесс &nbsp;изготовления в таких установках занимает около 10 - 12 часов, а так же сама установка имеет большие размеры.</span>
                </li>
                <li style="text-align: left;">
                  <span style="font-size: 14px;">В автоклаве можно готовить продукцию как <span style="font-weight: bold;">в стеклянных</span>, так и <span style="font-weight: bold;">в железных банках</span>, для которых дополнительно необходимо специальное оборудование. По стоимости одна железная банка обойдется примерно столько же, сколько стоит обычная стеклянная.</span>
                </li>
                <li>
                  <span style="font-size: 14px;">Для того что бы <span style="font-weight: bold;">закатки не по взрывались</span> необходимо соблюсти два основных правила: не долаживать продукцию до крышки банки&nbsp;на 1,5 - 2 см. и использовать свежие продукты, так как у испорченных повышенное газовыделение, за счет имеющихся там бактерий.</span>
                </li>
                <li
                ><span style="font-size: 14px; font-weight: bold;">Рецепт свинины тушеной в автоклаве: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size: 14px;">Ингредиенты на пол-литровую банку: 480 г. мяса, 5 г. соли, 7 г. лука репчатого, перец черный горошек - 3 шт, лавровый лист - &nbsp;1 шт. &nbsp; &nbsp;Технология приготовления: Вымыть банки и крышки, нарезать мясо на куски массой 50 - 100 г., нарезать лук, уложить на дно банки перец черный и лавровый лист, перемешать мясо с нарезанным луком, заполнить банку таким образом, что бы оставался воздушный зазор в 1,5 - 2 см (согласно инструкции), закатать банки, начать процесс стерилизации.</span>
              </li>

              <li
              ><span style="font-size: 14px; font-weight: bold;">Если Вы где-то нашли дешевле, сообщите нам об этом и Мы снизим для Вас цену. </span><span style="font-size: 14px;"></span>
            </li>


            <li
            ><span style="font-size: 14px; font-weight: bold;">За любой консультацией</span><span style="font-size: 14px;"></span> обращайтесь по телефонам: <span style="font-size: 14px; font-weight: bold;">+37529 7379222 (МТС) или +37529 3319156 (VELCOM) </span> 
          </li>
        </ul><p>
      </p>
    </div>
  </div>
</div>
<div class="art-layout-cell art-content"><article class="art-post art-article">

  <%= yield %>

</article></div>
</div>
</div>
</div><footer class="art-footer">
<p>ИП Патреев И.И., УНП:691751618</p><p>Телефоны: +37529 7379222 или +37529 3319156</p><p>Минск, 2015<br></p>
</footer>

</div>
<p class="art-page-footer">
  <!-- <span id="art-footnote-links"><a href="http://www.artisteer.com/" target="_blank">Web Template</a> created with Artisteer.</span> -->
</p>
</div>



</body>


</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_area :user_name %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_area :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Список заказов:</h1>


<table class="art-article" style="width: 100%; ">
  <tbody>
    <tr>
      <td style="width: 20%; text-align: center; "><span style="font-weight: bold; text-align: center; ">Выбор товара:</span><br>
      </td>
      <td style="width: 10%; text-align: center; "><span style="font-weight: bold; text-align: center; ">Количество:</span>
      </td>
      <td style="width: 23%; text-align: center; "><span style="font-weight: bold; text-align: center; ">Адрес:</span><br>
      </td>
      <td style="width: 23%; text-align: center; "><span style="font-weight: bold; text-align: center; ">ФИО:</span><br>
      </td>
      <td style="width: 23%; text-align: center; "><span style="font-weight: bold; text-align: center; ">Телефон:</span><br>
      </td>
    </tr>
    <tr>
     <% @orders.each do |order| %>
     <td style="width: 20%; text-align: center; ">
      <%= order.name %>
    </td>
    <td style="width: 20%; text-align: center; ">
      <%= order.count %>
    </td>
    <td style="width: 20%; text-align: center;">
      <%= order.adress %>
    </td>
    <td style="width: 20%; text-align: center;">
      <%= order.user_name %>
    </td>
    <td style="width: 20%; text-align: center;">
      <%= order.telephone %>
    </td>
  </tr>
  <tr>
   <% if user_signed_in? %>
    <% if current_user.email == 'patreewigor@yandex.ru' %>
      <td><%= link_to 'Show', order %></td>
      <td><%= link_to 'Edit', edit_order_path(order) %></td>
      <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
   <% end %>
   </tr>

   <% end %>
 </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @order.count %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @order.adress %>
</p>

<p>
  <strong>User name:</strong>
  <%= @order.user_name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @order.telephone %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.price %></td>
        <td><%= product.currency %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @product.currency %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>